version: 2
jobs:
  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make ci-setup
      - run: make ci
  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make ci-setup
      - run: make ci
  vs-ponyc-master-2:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make ci-setup
      - run: make ci
  nightly-release:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make ci-setup
      - run: make release

workflows:
  version: 2
  commit:
    jobs:
      - vs-ponyc-master # TODO: use vs-ponyc-release on next release
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master-2
      - nightly-release
