version: 2
jobs:
  vs-ponyc-master:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make ci-setup
      - run: make ci
  vs-ponyc-release:
    docker:
      - image: ponylang/ponyc:release
    steps:
      - checkout
      - run: make ci-setup
      - run: make ci
  vs-ponyc-master-2:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - run: make ci-setup
      - run: make ci
  nightly-release:
    docker:
      - image: ponylang/ponyc:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: make ci-setup
      - run: make release

workflows:
  version: 2
  commit:
    jobs:
      - vs-ponyc-master # TODO: use vs-ponyc-release on next release
  nightly:
    triggers:
      - schedule:
          cron: "* * * * *"
          filters:
            branches:
              only: master
    jobs:
      - vs-ponyc-master-2
      - nightly-release
